  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/mydb
      username: root
      password: root
    cloud:
      stream:
        bindings:
          subscribe-in-0:
            destination: subscriber_channel
  server:
    port: 8082



